import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: "#f9f9f9",
    },
    title: {
        fontSize: 32,
        fontWeight: "bold",
        marginBottom: 20,
        color: "#4b0082",
    },
    titleInput: {
        fontSize: 24,
        fontWeight: "bold",
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: "#ccc",
    },
    descriptionInput: {
        fontSize: 16,
        flex: 1,
        textAlignVertical: "top",
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 8,
        padding: 10,
        backgroundColor: "#fff",
    },
    inputWrapper: {
        flexDirection: "row",
        marginBottom: 20,
    },
    inputBox: {
        flex: 1,
        borderColor: "#6a0dad",
        borderWidth: 1,
        borderRadius: 8,
        padding: 10,
        marginRight: 10,
        backgroundColor: "#fff",
    },
    addButton: {
        backgroundColor: "#8a2be2",
        color: "white",
        borderRadius: 8,
        padding: 10,
        justifyContent: "center",
        alignItems: "center",
    },
    addButtonText: {
        color: "white",
        fontWeight: "bold",
    },
    listItem: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 10,
        marginBottom: 10,
        borderRadius: 8,
        backgroundColor: "#f9f9f9",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    task: {
        fontSize: 16,
        flex: 1,
        marginHorizontal: 10,
    },
    completeButton: {
        justifyContent: "center",
        alignItems: "center",
        width: 30,
        height: 30,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: "rgb(63, 39, 99)", 
        backgroundColor: "rgb(88, 53, 139)", 
    },
    deleteButton: {
        backgroundColor: "#e8648b", 
        width: 30,
        height: 30,
        borderRadius: 15,
        justifyContent: "center",
        alignItems: "center",
    },
    buttonText: {
        fontSize: 18,
        color: "white", 
        fontWeight: "bold",
        textAlign: "center",
    },
    deleteButtonText: {
        lineHeight: 30,
        fontSize: 14,
    },
    error: {
        color: "#ff0000",
        marginBottom: 10,
    },
    iconContainer: {
        marginRight: 10,
    },
});